//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class produk
    {
        public int Id { get; set; }
        public string tgl_produksi { get; set; }
        public string shift { get; set; }
        public string kode_produk { get; set; }
        public string jumlah_produk { get; set; }
    }
}
